aia:
  deploy: test
  init: test
  custom:
    - git init
  vars:
    dir: test

mojall:
  deploy: test
  init: test

deployer-sample:
  init: clone
  deploy: clone
  vars:
    dir: deployer-sample
    repo: 'https://github.com/sina-byn/deployer-sample.git'
